---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bgd
  name: bgd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bgd
  strategy: {}
  template:
    metadata:
      labels:
        app: bgd
      annotations:
        # Add the hash of the ConfigMap content here
        configmap-hash: "{{ .ConfigMap | sha256sum }}"
    spec:
      containers:
      - image: quay.io/rhdevelopers/bgd:1.0.0
        name: bgd
        envFrom:
          - configMapRef:
                name: my-configmap
        resources: {}
---
